# Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
%pip install numpy 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 8.7 MB/s eta 0:00:00a 0:00:01


In [ ]:
import numpy as np #type: ignore

# 1D array
array1 = np.array([1, 2, 3, 4, 5])
print(array1)    # [1 2 3 4 5]
print(array1.shape) # single dimension array

[1 2 3 4 5]
(5,)


In [ ]:
# 2D array
array2 = np.array([1,2,3,4,5])
array2.reshape(1,5)  # 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
# 3D array
array3 = np.array([1,2,3,4,5,6,7,8,9]) 
array3.reshape(3,3)  # 3 rows 3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 2D array with multiple rows
array2=np.array([[1,2,3,4,5],[2,3,4,5,6]]) 
print(array2)   # [[1 2 3 4 5]
print(array2.shape) # 2 rows 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0, 10, 2) # (start, stop, step) 0, 2, 4, 6, 8
print(np.arange(0, 10, 2).shape) # single dimension array
np.arange(0, 10, 2).reshape(5,1) # 5 rows 1 column

(5,)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4)) # 3 rows 4 columns with all 1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# Identity matrix
np.eye(3) # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Attributes of Numpy Array

In [35]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)
print("Shape:", array.shape)  # Output: (2, 3)
print("Number of dimensions:", array.ndim)  # Output: 2
print("Size (Number of Elements):", array.size)  # Output: 6
print("Data type:", array.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", array.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (Number of Elements): 6
Data type: int64
Item size (in bytes): 8


##### Numpy Vectorized Operation

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise Addition
print("Addition:", arr1+arr2)

# Element Wise Subtraction
print("Subtraction:", arr1-arr2)

# Elementn Wise Multiplication
print("Multiplication:", arr1 * arr2)
 
# Element Wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


##### Universal Function:
These are fuctions that apply to entire array

In [ ]:
arr=np.array([2,3,4,5,6])
# Square Root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))
 
# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


##### Array Slicing & Indexing

In [26]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
print(arr[1:,1:3])

[[100 100]
 [100 100]]


In [42]:
print(arr[0][0])
print(arr[0:2,2:])

100
[[  3   4]
 [100 100]]


In [41]:
arr[1:,2:]

array([[100, 100],
       [100, 100]])

In [49]:
arr[1: 3, 1: 3]

array([[100, 100],
       [100, 100]])

##### Modify Array Elements


In [51]:
arr[0,0] = 100 
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statistical Concepts: Normalization

In [32]:
# To have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


##### Statistical Operations

In [33]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


##### Logical Operation

In [34]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])